spring:
  application:
    name: admin-service
#  datasource:  # Подключение к PostgreSQL из Docker
#    url: jdbc:postgresql://localhost:5432/kupidai
#    username: admin
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}:${random.value}
        health-check-path: /actuator/health
        health-check-interval: 10s

management:  # Для health checks
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
server:
  port: 8079