# services/api-gateway/src/main/resources/application.yml
server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:api-gateway}

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**

        - id: notifications-service
          uri: lb://notifications-service
          predicates:
            - Path=/api/notification/**

    consul:
      host: ${CONSUL_HOST:consul}
      port: ${CONSUL_PORT:8500}
      discovery:
        health-check-path: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always